#!/usr/bin/env bash
#Working on 4-if_9_say_hi, here the script displays hi on the 9th iteration.
i=1
while [ $i -lt 10 ];do
	if [ $i -eq 9 ]; then
		echo "Best School"
		echo "Hi"
	fi
		echo "Best School"
	((i++))
done
